### ISSUE TITLE
Handle buttons better

### ISSUE THREAD

**Issue by bentranter** [bentranter/default#5]
Right now, the situation with buttons is pretty frustrating. There isn't a way to make buttons that follows the immutable/composable pattern, and it's hard to create a way to do it that doesn't require a ton of boilerplate CSS.

It would be nice to be able to do something like,

``` HTML
<button class='btn bg-blue white no-border rise'>Click Me</button>
```

Which would translate to something like,

``` CSS
button {
  display: inline-block;
  position: relative;
  cursor: pointer;
  background-color: blue;
  color: white;
  border: none;
  transition-duration: .2s;
  transition-timing-function: ease-in-out;
  transition-property: box-shadow;
}

button:hover {
  box-shadow: 0 8px 17px 0 rgba(0, 0, 0, 0.2);
  transition-delay: 0s;
}
```

This example gives you kind of material-design feel to your button. I think the solution lies in the classes that would be used to define the hover effects, for example, the class `rise` could look something like,

``` CSS
.rise:hover {
  box-shadow: 0 8px 17px 0 rgba(0, 0, 0, 0.2);
  transition-delay: 0s;
}
```

So, `rise` would **only** have hover effects, and would only be used to style an element's hover state. Would it be a good idea to prefix these classes with something, like `h-rise`, to denote that it's something that only applies to hover states?

The prefixing might not be a bad idea, especially since as immutable/composable JavaScript classes will start to get introduced, some `js-` classes will start to show up.
